services:
  # Service 1: The PostgreSQL Database
  postgres_db:
    image: postgres:16
    container_name: ecommerce_db_container
    hostname: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ecommerce_postgres_data:/var/lib/postgresql/data

  # Service 2: The ETL Pipeline
  etl_service:
    build:
      context: ./etl
    container_name: etl_pipeline
    depends_on:
      - postgres_db
    volumes:
      - ./data:/app/data
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres_db 
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
    command: ["./wait-for-postgres.sh", "python", "etl_pipeline.py"]

volumes:
  ecommerce_postgres_data: